version: '3.8'

services:
  manager1:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      - container_network
  manager2:
    build: .
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      - container_network

networks:
  container_network:
    driver: bridge