services:
  manager1:
    container_name: manager1
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      - container_network
    command: [ "./container-manager", "--jrpc-port=8080", "--p2p-port=4041" ]
  manager2:
    container_name: manager2
    build: .
    ports:
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      - container_network
    command: [ "./container-manager", "--jrpc-port=8081", "--p2p-port=4042" ]

networks:
  container_network:
    driver: bridge